### ISSUE TITLE
ng test does not work with jest

### ISSUE THREAD

**Issue by gregbown** [brandonroberts/ngrx-ngconf-2018#1]
Hi Brandon,

I've been going through multiple examples of Angular CLI projects that use Jest and it seems that in every case it breaks the CLI's built in ng test with Karma functionality because certain methods added via jest are undefined with karma; e.g.
```
Property 'toMatchSnapshot' does not exist on type 'Matchers<ComponentTestFixture<LoginPageComponent>>'
```
I am a bit reluctant to stray too far from what the Angular team is using, working on a large project, however; I cannot find any current, pure Jasmine-Karma examples for testing ngrx and I am unable to see a way forward using both testing suites. The ngrx platform example seems to be the same, where there isn't really a clear way to unravel the jest pieces from the tests to strictly implement Angular's supported test suites.

Am I correct that jest cannot be integrated into a project without breaking ng test?

Suggestion:
If there was work on opening up testing with a built in option directly inside the CLI, something like below, that would be awesome!
```
        "test": {
          "builder": "@angular-devkit/build-angular:jest",
          "options": {
            "main": "src/test.ts",
            "config": "./jest.conf.js",
```

Thank you for the examples, btw!

**Comment by brandonroberts** [comment]
Hey @gregbown, its correct that Jest is not baked into the CLI as a first class citizen. I would not suggest trying to mix the two suites together also. The architect package in the CLI supports this if I'm not mistaken, but no package has been built yet to support Jest in this way.

If you write tests without using snapshots and query DOM elements to verify content, then Karma will work just fine for testing. I hope this helps.
