### ISSUE TITLE
ofType error in '@ngrx/effects'

### ISSUE THREAD

**Issue by snatuva** [brandonroberts/ngrx-ngconf-2018#3]
Hi Brandon, I just watched your talk on ngconf on auth. 
I am trying to use your code and build auth with ngrx. but i am unable to get ofType in '@ngrx/effects' module. please help how to get ofType.

thanks.

**Comment by brandonroberts** [comment]
If you're installing the latest version as of right now (V7). You'll need to use the `ofType` operator imported from `@ngrx/effects` instead of the instance operator.

**Comment by snatuva** [comment]
I tried to import in the auth.effects.ts file
`import { Actions, Effect, ofType} from '@ngrx/effects';`

is this correct ?

**Comment by brandonroberts** [comment]
Yes, that's correct.

**Comment by snatuva** [comment]
Thank you, its working now.. And also need to put ofType inside pipe.
:)

**Comment by brandonroberts** [comment]
Cool!
